name: 'ascend test / nightly-a3'

on:
  schedule:
      # Run test at 24:00 Beijing time (UTC+8)
      - cron: "0 0 * * *"
  pull_request: 
    branches:
      - 'main'
    paths:
      - ".github/workflows/nightly-test-ascend-a2.yml"
  workflow_dispatch:

concurrency:
  group: ascend-nightly-test-${{ github.ref }}-a2
  cancel-in-progress: true

jobs:
  nightly-performance-multi-node-tests:
    name: multi-node
    if: ${{ (github.repository == 'sgl-project/sglang' || github.event_name == 'pull_request') }}
    needs: nightly-performance-pd-separation-tests
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        test_config:
          - name: test_ascend_qwen3_235b_w8a8_16p_in2k_out2k_50ms
            node_size: 2
            test_case: test/nightly/ascend/performance/test_ascend_qwen3_235b_w8a8_16p_in2k_out2k_50ms.py
    uses: ./.github/workflows/nightly-test-npu-multi-node.yml
    with:
      soc_version: a2
      runner: linux-amd64-cpu-0
      image: 'swr.cn-southwest-2.myhuaweicloud.com/base_image/dockerhub/lmsysorg/sglang:cann8.3.rc2-910b-release1225'
      test_config_name: ${{ matrix.test_config.name }}
      node_size: ${{ matrix.test_config.node_size }}
      test_case: ${{ matrix.test_config.test_case }}

